# Generated by Django 4.0.6 on 2022-07-22 22:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0003_remove_trait_moves_move'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_traumatized', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='trait',
            name='is_magic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trait',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='traits.category'),
            preserve_default=False,
        ),
    ]
