# Generated by Django 4.0.6 on 2022-07-23 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tradition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.holiday')),
            ],
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.month')),
            ],
        ),
        migrations.AddField(
            model_name='month',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.season'),
        ),
        migrations.CreateModel(
            name='Lack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.month')),
            ],
        ),
        migrations.CreateModel(
            name='HolidayMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.holiday')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('trigger', models.CharField(max_length=400)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.month')),
            ],
        ),
        migrations.CreateModel(
            name='EffectMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.effect')),
            ],
        ),
        migrations.AddField(
            model_name='effect',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.event'),
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.holiday')),
            ],
        ),
    ]
