# Generated by Django 4.0.6 on 2022-07-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='custom',
            name='text',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='effect',
            name='text',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='effectmove',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='effectmove',
            name='text',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='trigger',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='holidaymove',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='holidaymove',
            name='text',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='lack',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lack',
            name='text',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='month',
            name='description',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='month',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='month',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sign',
            name='text',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='tradition',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tradition',
            name='text',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
