# Generated by Django 4.0.6 on 2022-07-31 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0002_alter_custom_id_alter_custom_text_alter_effect_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seasons.season'),
            preserve_default=False,
        ),
    ]
