# Generated by Django 4.0.6 on 2022-08-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0004_alter_event_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='trigger',
            field=models.CharField(max_length=600, unique=True),
        ),
    ]
