# Generated by Django 4.0.6 on 2022-08-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0006_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='text',
            field=models.CharField(max_length=400),
        ),
    ]
