# Generated by Django 4.0.6 on 2022-08-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0007_alter_sign_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='text',
            field=models.CharField(max_length=400),
        ),
    ]
