# Generated by Django 4.0.6 on 2022-07-31 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0003_alter_option_non_magic_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
