# Generated by Django 4.0.6 on 2022-07-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_alter_option_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
