# Generated by Django 4.0.6 on 2022-07-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0005_alter_option_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='non_magic_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='non_traumatized_or_magic_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='non_traumatized_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
