# Generated by Django 4.0.6 on 2022-07-23 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_prompt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SignatureMoveOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SignatureMoves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=400)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playbooks.playbook')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalMoves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playbooks.playbook')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('personality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playbooks.personality')),
            ],
        ),
        migrations.AddField(
            model_name='personality',
            name='playbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playbooks.playbook'),
        ),
        migrations.CreateModel(
            name='HistoryOptions',
            fields=[
                ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='options.option')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playbooks.history')),
            ],
            bases=('options.option',),
        ),
        migrations.AddField(
            model_name='history',
            name='playbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playbooks.playbook'),
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playbooks.playbook')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playbooks.playbook')),
            ],
        ),
    ]
