# Generated by Django 4.0.6 on 2022-07-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0002_relationship_playbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personalityoption',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='playbook',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='prompt',
            field=models.CharField(max_length=100),
        ),
    ]
