# Generated by Django 4.0.6 on 2022-07-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0005_history_prompt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignatureMoveOptions',
        ),
        migrations.RemoveField(
            model_name='signaturemoves',
            name='prompt',
        ),
        migrations.AddField(
            model_name='signaturemoves',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
