# Generated by Django 4.0.6 on 2022-07-23 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
        ('playbooks', '0006_delete_signaturemoveoptions_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoryOptions',
            new_name='HistoryOption',
        ),
        migrations.RenameModel(
            old_name='SeasonalMoves',
            new_name='SeasonalMove',
        ),
        migrations.RenameModel(
            old_name='SignatureMoves',
            new_name='SignatureMove',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='prompt',
            new_name='name',
        ),
    ]
