# Generated by Django 4.0.6 on 2022-07-23 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0007_rename_historyoptions_historyoption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='name',
            new_name='prompt',
        ),
    ]
