# Generated by Django 4.0.6 on 2022-07-29 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0012_alter_personalityoption_personality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personality',
            name='playbook',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='playbooks.playbook'),
        ),
        migrations.AlterField(
            model_name='personalityoption',
            name='personality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playbooks.personality'),
        ),
    ]
