# Generated by Django 4.0.6 on 2022-07-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0014_alter_playbook_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonalmove',
            name='text',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
