# Generated by Django 4.0.6 on 2022-07-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0016_alter_personalityoption_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonalmove',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
