# Generated by Django 4.0.6 on 2022-07-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0017_alter_seasonalmove_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='text',
            field=models.CharField(max_length=50),
        ),
    ]
