# Generated by Django 4.0.6 on 2022-07-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('non_magic_text', models.CharField(blank=True, max_length=100, null=True)),
                ('non_traumatized_text', models.CharField(blank=True, max_length=100, null=True)),
                ('non_traumatized_or_magic_text', models.CharField(blank=True, max_length=100, null=True)),
                ('is_magical', models.BooleanField(default=False)),
                ('is_traumatized', models.BooleanField(default=False)),
            ],
        ),
    ]
