# Generated by Django 4.0.6 on 2022-07-23 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=300)),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natures.nature')),
            ],
        ),
        migrations.CreateModel(
            name='Lore',
            fields=[
                ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='options.option')),
                ('prompt', models.CharField(max_length=200)),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natures.nature')),
            ],
            bases=('options.option',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natures.nature')),
            ],
        ),
        migrations.CreateModel(
            name='Aesthetic',
            fields=[
                ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='options.option')),
                ('name', models.CharField(max_length=100)),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natures.nature')),
            ],
            bases=('options.option',),
        ),
    ]
