# Generated by Django 4.0.6 on 2022-07-23 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='playbook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='playbooks.playbook'),
            preserve_default=False,
        ),
    ]
