# Generated by Django 4.0.6 on 2022-07-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0004_rename_personality_prompt_personality_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='prompt',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
