# Generated by Django 4.0.6 on 2022-07-22 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='options',
        ),
        migrations.AddField(
            model_name='trait',
            name='moves',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trait',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
