# Generated by Django 4.0.6 on 2022-07-26 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0004_category_trait_is_magic_trait_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='TraitCategory',
        ),
    ]
