# Generated by Django 4.0.6 on 2022-07-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0005_rename_category_traitcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='description',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trait',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='traitcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='traitcategory',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
