# Generated by Django 4.0.6 on 2022-07-27 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0007_remove_trait_category_traitcategory_traits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traitcategory',
            name='traits',
        ),
        migrations.AddField(
            model_name='trait',
            name='traits',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='traits.traitcategory'),
            preserve_default=False,
        ),
    ]
