# Generated by Django 4.0.6 on 2022-07-27 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0008_remove_traitcategory_traits_trait_traits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trait',
            old_name='traits',
            new_name='trait_category',
        ),
    ]
