# Generated by Django 4.0.6 on 2022-07-27 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0009_rename_traits_trait_trait_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trait',
            old_name='trait_category',
            new_name='category',
        ),
    ]
