# Generated by Django 4.0.6 on 2022-07-27 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0010_rename_trait_category_trait_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='trait',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='traits.trait'),
        ),
        migrations.AlterField(
            model_name='trait',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='traits.traitcategory'),
        ),
    ]
