# Generated by Django 4.0.6 on 2022-07-23 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natures', '0002_remove_lore_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aesthetic',
            name='name',
        ),
    ]
