# Generated by Django 4.0.6 on 2022-07-23 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('natures', '0003_remove_aesthetic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='nature',
        ),
        migrations.AddField(
            model_name='nature',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='natures.category'),
            preserve_default=False,
        ),
    ]
