# Generated by Django 4.0.6 on 2022-07-26 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natures', '0004_remove_category_nature_nature_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='NatureCategory',
        ),
    ]
