# Generated by Django 4.0.6 on 2022-07-27 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natures', '0007_alter_aesthetic_nature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Move',
            new_name='NatureMove',
        ),
    ]
