# Generated by Django 4.0.6 on 2022-07-27 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('natures', '0008_rename_move_naturemove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aesthetic',
            name='nature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='natures.nature'),
        ),
        migrations.AlterField(
            model_name='lore',
            name='nature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='natures.nature'),
        ),
        migrations.AlterField(
            model_name='nature',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='natures.naturecategory'),
        ),
        migrations.AlterField(
            model_name='naturemove',
            name='nature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='natures.nature'),
        ),
    ]
